//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="UsuarioWS.PersonaWS")]
    public interface PersonaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Bussiness.UsuarioWS.modificarPersonaResponse modificarPersona(Bussiness.UsuarioWS.modificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaResponse")]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.modificarPersonaResponse> modificarPersonaAsync(Bussiness.UsuarioWS.modificarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Bussiness.UsuarioWS.eliminarPersonaResponse eliminarPersona(Bussiness.UsuarioWS.eliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaResponse")]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.eliminarPersonaResponse> eliminarPersonaAsync(Bussiness.UsuarioWS.eliminarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Bussiness.UsuarioWS.listarPersonasResponse listarPersonas(Bussiness.UsuarioWS.listarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasResponse")]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.listarPersonasResponse> listarPersonasAsync(Bussiness.UsuarioWS.listarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Bussiness.UsuarioWS.insertarPersonaResponse insertarPersona(Bussiness.UsuarioWS.insertarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaResponse")]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.insertarPersonaResponse> insertarPersonaAsync(Bussiness.UsuarioWS.insertarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Bussiness.UsuarioWS.obtenerPersonaResponse obtenerPersona(Bussiness.UsuarioWS.obtenerPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaResponse")]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.obtenerPersonaResponse> obtenerPersonaAsync(Bussiness.UsuarioWS.obtenerPersonaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoPersona {
        
        /// <remarks/>
        LECTOR,
        
        /// <remarks/>
        BIBLIOTECARIO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivelDeIngles {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum turnos {
        
        /// <remarks/>
        MAÑANA,
        
        /// <remarks/>
        TARDE,
        
        /// <remarks/>
        NOCHE,
        
        /// <remarks/>
        FULLTIME,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.tipoPersona tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.nivelDeIngles nivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.turnos turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool vigente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public modificarPersonaRequest() {
        }
        
        public modificarPersonaRequest(int idPersona, string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            this.idPersona = idPersona;
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.direccion = direccion;
            this.telefono = telefono;
            this.correo = correo;
            this.contrasenha = contrasenha;
            this.tipo = tipo;
            this.nivel = nivel;
            this.turno = turno;
            this.fechaContratoInicio = fechaContratoInicio;
            this.fechaContratoFinal = fechaContratoFinal;
            this.vigente = vigente;
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPersonaResponse() {
        }
        
        public modificarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class personaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string direccionField;
        
        private System.DateTime fechaContratoFinalField;
        
        private bool fechaContratoFinalFieldSpecified;
        
        private System.DateTime fechaContratoInicioField;
        
        private bool fechaContratoInicioFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string maternoField;
        
        private nivelDeIngles nivelField;
        
        private bool nivelFieldSpecified;
        
        private string nombreField;
        
        private string paternoField;
        
        private sedeDTO sedeField;
        
        private string telefonoField;
        
        private tipoPersona tipoField;
        
        private bool tipoFieldSpecified;
        
        private turnos turnoField;
        
        private bool turnoFieldSpecified;
        
        private bool vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaContratoFinal {
            get {
                return this.fechaContratoFinalField;
            }
            set {
                this.fechaContratoFinalField = value;
                this.RaisePropertyChanged("fechaContratoFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoFinalSpecified {
            get {
                return this.fechaContratoFinalFieldSpecified;
            }
            set {
                this.fechaContratoFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaContratoInicio {
            get {
                return this.fechaContratoInicioField;
            }
            set {
                this.fechaContratoInicioField = value;
                this.RaisePropertyChanged("fechaContratoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoInicioSpecified {
            get {
                return this.fechaContratoInicioFieldSpecified;
            }
            set {
                this.fechaContratoInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public nivelDeIngles nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public sedeDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public tipoPersona tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public turnos turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasRequest {
        
        public listarPersonasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.personaDTO[] @return;
        
        public listarPersonasResponse() {
        }
        
        public listarPersonasResponse(Bussiness.UsuarioWS.personaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.tipoPersona tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.nivelDeIngles nivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.turnos turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool vigente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public insertarPersonaRequest() {
        }
        
        public insertarPersonaRequest(string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.direccion = direccion;
            this.telefono = telefono;
            this.correo = correo;
            this.contrasenha = contrasenha;
            this.tipo = tipo;
            this.nivel = nivel;
            this.turno = turno;
            this.fechaContratoInicio = fechaContratoInicio;
            this.fechaContratoFinal = fechaContratoFinal;
            this.vigente = vigente;
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPersonaResponse() {
        }
        
        public insertarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public obtenerPersonaRequest() {
        }
        
        public obtenerPersonaRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bussiness.UsuarioWS.personaDTO @return;
        
        public obtenerPersonaResponse() {
        }
        
        public obtenerPersonaResponse(Bussiness.UsuarioWS.personaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonaWSChannel : Bussiness.UsuarioWS.PersonaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaWSClient : System.ServiceModel.ClientBase<Bussiness.UsuarioWS.PersonaWS>, Bussiness.UsuarioWS.PersonaWS {
        
        public PersonaWSClient() {
        }
        
        public PersonaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bussiness.UsuarioWS.modificarPersonaResponse Bussiness.UsuarioWS.PersonaWS.modificarPersona(Bussiness.UsuarioWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersona(request);
        }
        
        public int modificarPersona(int idPersona, string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            Bussiness.UsuarioWS.modificarPersonaRequest inValue = new Bussiness.UsuarioWS.modificarPersonaRequest();
            inValue.idPersona = idPersona;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.nivel = nivel;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.vigente = vigente;
            inValue.idSede = idSede;
            Bussiness.UsuarioWS.modificarPersonaResponse retVal = ((Bussiness.UsuarioWS.PersonaWS)(this)).modificarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.modificarPersonaResponse> Bussiness.UsuarioWS.PersonaWS.modificarPersonaAsync(Bussiness.UsuarioWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bussiness.UsuarioWS.modificarPersonaResponse> modificarPersonaAsync(int idPersona, string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            Bussiness.UsuarioWS.modificarPersonaRequest inValue = new Bussiness.UsuarioWS.modificarPersonaRequest();
            inValue.idPersona = idPersona;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.nivel = nivel;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.vigente = vigente;
            inValue.idSede = idSede;
            return ((Bussiness.UsuarioWS.PersonaWS)(this)).modificarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bussiness.UsuarioWS.eliminarPersonaResponse Bussiness.UsuarioWS.PersonaWS.eliminarPersona(Bussiness.UsuarioWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public int eliminarPersona(int idPersona) {
            Bussiness.UsuarioWS.eliminarPersonaRequest inValue = new Bussiness.UsuarioWS.eliminarPersonaRequest();
            inValue.idPersona = idPersona;
            Bussiness.UsuarioWS.eliminarPersonaResponse retVal = ((Bussiness.UsuarioWS.PersonaWS)(this)).eliminarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.eliminarPersonaResponse> Bussiness.UsuarioWS.PersonaWS.eliminarPersonaAsync(Bussiness.UsuarioWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bussiness.UsuarioWS.eliminarPersonaResponse> eliminarPersonaAsync(int idPersona) {
            Bussiness.UsuarioWS.eliminarPersonaRequest inValue = new Bussiness.UsuarioWS.eliminarPersonaRequest();
            inValue.idPersona = idPersona;
            return ((Bussiness.UsuarioWS.PersonaWS)(this)).eliminarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bussiness.UsuarioWS.listarPersonasResponse Bussiness.UsuarioWS.PersonaWS.listarPersonas(Bussiness.UsuarioWS.listarPersonasRequest request) {
            return base.Channel.listarPersonas(request);
        }
        
        public Bussiness.UsuarioWS.personaDTO[] listarPersonas() {
            Bussiness.UsuarioWS.listarPersonasRequest inValue = new Bussiness.UsuarioWS.listarPersonasRequest();
            Bussiness.UsuarioWS.listarPersonasResponse retVal = ((Bussiness.UsuarioWS.PersonaWS)(this)).listarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.listarPersonasResponse> Bussiness.UsuarioWS.PersonaWS.listarPersonasAsync(Bussiness.UsuarioWS.listarPersonasRequest request) {
            return base.Channel.listarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bussiness.UsuarioWS.listarPersonasResponse> listarPersonasAsync() {
            Bussiness.UsuarioWS.listarPersonasRequest inValue = new Bussiness.UsuarioWS.listarPersonasRequest();
            return ((Bussiness.UsuarioWS.PersonaWS)(this)).listarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bussiness.UsuarioWS.insertarPersonaResponse Bussiness.UsuarioWS.PersonaWS.insertarPersona(Bussiness.UsuarioWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersona(request);
        }
        
        public int insertarPersona(string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            Bussiness.UsuarioWS.insertarPersonaRequest inValue = new Bussiness.UsuarioWS.insertarPersonaRequest();
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.nivel = nivel;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.vigente = vigente;
            inValue.idSede = idSede;
            Bussiness.UsuarioWS.insertarPersonaResponse retVal = ((Bussiness.UsuarioWS.PersonaWS)(this)).insertarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.insertarPersonaResponse> Bussiness.UsuarioWS.PersonaWS.insertarPersonaAsync(Bussiness.UsuarioWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bussiness.UsuarioWS.insertarPersonaResponse> insertarPersonaAsync(string nombre, string paterno, string materno, string direccion, string telefono, string correo, string contrasenha, Bussiness.UsuarioWS.tipoPersona tipo, Bussiness.UsuarioWS.nivelDeIngles nivel, Bussiness.UsuarioWS.turnos turno, System.DateTime fechaContratoInicio, System.DateTime fechaContratoFinal, bool vigente, int idSede) {
            Bussiness.UsuarioWS.insertarPersonaRequest inValue = new Bussiness.UsuarioWS.insertarPersonaRequest();
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.nivel = nivel;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.vigente = vigente;
            inValue.idSede = idSede;
            return ((Bussiness.UsuarioWS.PersonaWS)(this)).insertarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bussiness.UsuarioWS.obtenerPersonaResponse Bussiness.UsuarioWS.PersonaWS.obtenerPersona(Bussiness.UsuarioWS.obtenerPersonaRequest request) {
            return base.Channel.obtenerPersona(request);
        }
        
        public Bussiness.UsuarioWS.personaDTO obtenerPersona(int idPersona) {
            Bussiness.UsuarioWS.obtenerPersonaRequest inValue = new Bussiness.UsuarioWS.obtenerPersonaRequest();
            inValue.idPersona = idPersona;
            Bussiness.UsuarioWS.obtenerPersonaResponse retVal = ((Bussiness.UsuarioWS.PersonaWS)(this)).obtenerPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bussiness.UsuarioWS.obtenerPersonaResponse> Bussiness.UsuarioWS.PersonaWS.obtenerPersonaAsync(Bussiness.UsuarioWS.obtenerPersonaRequest request) {
            return base.Channel.obtenerPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bussiness.UsuarioWS.obtenerPersonaResponse> obtenerPersonaAsync(int idPersona) {
            Bussiness.UsuarioWS.obtenerPersonaRequest inValue = new Bussiness.UsuarioWS.obtenerPersonaRequest();
            inValue.idPersona = idPersona;
            return ((Bussiness.UsuarioWS.PersonaWS)(this)).obtenerPersonaAsync(inValue);
        }
    }
}
