//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.CreadorMaterialWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="CreadorMaterialWS.CreadorMaterialWS")]
    public interface CreadorMaterialWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/existeRelacionReques" +
            "t", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/existeRelacionRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.CreadorMaterialWS.existeRelacionResponse existeRelacion(WA_Prueba.CreadorMaterialWS.existeRelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/existeRelacionReques" +
            "t", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/existeRelacionRespon" +
            "se")]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.existeRelacionResponse> existeRelacionAsync(WA_Prueba.CreadorMaterialWS.existeRelacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/desasociarMaterialCr" +
            "eadorRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/desasociarMaterialCr" +
            "eadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse desasociarMaterialCreador(WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/desasociarMaterialCr" +
            "eadorRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/desasociarMaterialCr" +
            "eadorResponse")]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse> desasociarMaterialCreadorAsync(WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/asociarMaterialCread" +
            "orRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/asociarMaterialCread" +
            "orResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse asociarMaterialCreador(WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/asociarMaterialCread" +
            "orRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/asociarMaterialCread" +
            "orResponse")]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse> asociarMaterialCreadorAsync(WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarMaterialesPorC" +
            "readorRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarMaterialesPorC" +
            "readorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse listarMaterialesPorCreador(WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarMaterialesPorC" +
            "readorRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarMaterialesPorC" +
            "readorResponse")]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse> listarMaterialesPorCreadorAsync(WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarCreadoresPorMa" +
            "terialRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarCreadoresPorMa" +
            "terialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse listarCreadoresPorMaterial(WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarCreadoresPorMa" +
            "terialRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/CreadorMaterialWS/listarCreadoresPorMa" +
            "terialResponse")]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse> listarCreadoresPorMaterialAsync(WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existeRelacion", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class existeRelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCreador;
        
        public existeRelacionRequest() {
        }
        
        public existeRelacionRequest(int idMaterial, int idCreador) {
            this.idMaterial = idMaterial;
            this.idCreador = idCreador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existeRelacionResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class existeRelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public existeRelacionResponse() {
        }
        
        public existeRelacionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desasociarMaterialCreador", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class desasociarMaterialCreadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCreador;
        
        public desasociarMaterialCreadorRequest() {
        }
        
        public desasociarMaterialCreadorRequest(int idMaterial, int idCreador) {
            this.idMaterial = idMaterial;
            this.idCreador = idCreador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desasociarMaterialCreadorResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class desasociarMaterialCreadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public desasociarMaterialCreadorResponse() {
        }
        
        public desasociarMaterialCreadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="asociarMaterialCreador", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class asociarMaterialCreadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCreador;
        
        public asociarMaterialCreadorRequest() {
        }
        
        public asociarMaterialCreadorRequest(int idMaterial, int idCreador) {
            this.idMaterial = idMaterial;
            this.idCreador = idCreador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="asociarMaterialCreadorResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class asociarMaterialCreadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public asociarMaterialCreadorResponse() {
        }
        
        public asociarMaterialCreadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string edicionField;
        
        private editorialDTO editorialField;
        
        private int idMaterialField;
        
        private bool idMaterialFieldSpecified;
        
        private nivelDeIngles nivelField;
        
        private bool nivelFieldSpecified;
        
        private string portadaField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string edicion {
            get {
                return this.edicionField;
            }
            set {
                this.edicionField = value;
                this.RaisePropertyChanged("edicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public editorialDTO editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idMaterial {
            get {
                return this.idMaterialField;
            }
            set {
                this.idMaterialField = value;
                this.RaisePropertyChanged("idMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMaterialSpecified {
            get {
                return this.idMaterialFieldSpecified;
            }
            set {
                this.idMaterialFieldSpecified = value;
                this.RaisePropertyChanged("idMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public nivelDeIngles nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class editorialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEditorialField;
        
        private bool idEditorialFieldSpecified;
        
        private string nombreField;
        
        private string paisField;
        
        private string sitioWebField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEditorialSpecified {
            get {
                return this.idEditorialFieldSpecified;
            }
            set {
                this.idEditorialFieldSpecified = value;
                this.RaisePropertyChanged("idEditorialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sitioWeb {
            get {
                return this.sitioWebField;
            }
            set {
                this.sitioWebField = value;
                this.RaisePropertyChanged("sitioWeb");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class creadorDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idAutorField;
        
        private bool idAutorFieldSpecified;
        
        private string maternoField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        private string paternoField;
        
        private string seudonimoField;
        
        private tipoAutor tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAutorSpecified {
            get {
                return this.idAutorFieldSpecified;
            }
            set {
                this.idAutorFieldSpecified = value;
                this.RaisePropertyChanged("idAutorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string seudonimo {
            get {
                return this.seudonimoField;
            }
            set {
                this.seudonimoField = value;
                this.RaisePropertyChanged("seudonimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoAutor tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoAutor {
        
        /// <remarks/>
        AUTOR,
        
        /// <remarks/>
        TRADUCTOR,
        
        /// <remarks/>
        ILUSTRADOR,
        
        /// <remarks/>
        NARRADOR,
        
        /// <remarks/>
        EDITOR,
        
        /// <remarks/>
        GUIONISTA,
        
        /// <remarks/>
        DISENADOR_EDITORIAL,
        
        /// <remarks/>
        OTRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivelDeIngles {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMaterialesPorCreador", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarMaterialesPorCreadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCreador;
        
        public listarMaterialesPorCreadorRequest() {
        }
        
        public listarMaterialesPorCreadorRequest(int idCreador) {
            this.idCreador = idCreador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMaterialesPorCreadorResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarMaterialesPorCreadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.CreadorMaterialWS.materialDTO[] @return;
        
        public listarMaterialesPorCreadorResponse() {
        }
        
        public listarMaterialesPorCreadorResponse(WA_Prueba.CreadorMaterialWS.materialDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCreadoresPorMaterial", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarCreadoresPorMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public listarCreadoresPorMaterialRequest() {
        }
        
        public listarCreadoresPorMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCreadoresPorMaterialResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarCreadoresPorMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.CreadorMaterialWS.creadorDTO[] @return;
        
        public listarCreadoresPorMaterialResponse() {
        }
        
        public listarCreadoresPorMaterialResponse(WA_Prueba.CreadorMaterialWS.creadorDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreadorMaterialWSChannel : WA_Prueba.CreadorMaterialWS.CreadorMaterialWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreadorMaterialWSClient : System.ServiceModel.ClientBase<WA_Prueba.CreadorMaterialWS.CreadorMaterialWS>, WA_Prueba.CreadorMaterialWS.CreadorMaterialWS {
        
        public CreadorMaterialWSClient() {
        }
        
        public CreadorMaterialWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreadorMaterialWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreadorMaterialWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreadorMaterialWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.CreadorMaterialWS.existeRelacionResponse WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.existeRelacion(WA_Prueba.CreadorMaterialWS.existeRelacionRequest request) {
            return base.Channel.existeRelacion(request);
        }
        
        public bool existeRelacion(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.existeRelacionRequest inValue = new WA_Prueba.CreadorMaterialWS.existeRelacionRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            WA_Prueba.CreadorMaterialWS.existeRelacionResponse retVal = ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).existeRelacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.existeRelacionResponse> WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.existeRelacionAsync(WA_Prueba.CreadorMaterialWS.existeRelacionRequest request) {
            return base.Channel.existeRelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.existeRelacionResponse> existeRelacionAsync(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.existeRelacionRequest inValue = new WA_Prueba.CreadorMaterialWS.existeRelacionRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            return ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).existeRelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.desasociarMaterialCreador(WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest request) {
            return base.Channel.desasociarMaterialCreador(request);
        }
        
        public int desasociarMaterialCreador(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse retVal = ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).desasociarMaterialCreador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse> WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.desasociarMaterialCreadorAsync(WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest request) {
            return base.Channel.desasociarMaterialCreadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorResponse> desasociarMaterialCreadorAsync(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.desasociarMaterialCreadorRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            return ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).desasociarMaterialCreadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.asociarMaterialCreador(WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest request) {
            return base.Channel.asociarMaterialCreador(request);
        }
        
        public int asociarMaterialCreador(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse retVal = ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).asociarMaterialCreador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse> WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.asociarMaterialCreadorAsync(WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest request) {
            return base.Channel.asociarMaterialCreadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorResponse> asociarMaterialCreadorAsync(int idMaterial, int idCreador) {
            WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.asociarMaterialCreadorRequest();
            inValue.idMaterial = idMaterial;
            inValue.idCreador = idCreador;
            return ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).asociarMaterialCreadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.listarMaterialesPorCreador(WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest request) {
            return base.Channel.listarMaterialesPorCreador(request);
        }
        
        public WA_Prueba.CreadorMaterialWS.materialDTO[] listarMaterialesPorCreador(int idCreador) {
            WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest();
            inValue.idCreador = idCreador;
            WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse retVal = ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).listarMaterialesPorCreador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse> WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.listarMaterialesPorCreadorAsync(WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest request) {
            return base.Channel.listarMaterialesPorCreadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorResponse> listarMaterialesPorCreadorAsync(int idCreador) {
            WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest inValue = new WA_Prueba.CreadorMaterialWS.listarMaterialesPorCreadorRequest();
            inValue.idCreador = idCreador;
            return ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).listarMaterialesPorCreadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.listarCreadoresPorMaterial(WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest request) {
            return base.Channel.listarCreadoresPorMaterial(request);
        }
        
        public WA_Prueba.CreadorMaterialWS.creadorDTO[] listarCreadoresPorMaterial(int idMaterial) {
            WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest inValue = new WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse retVal = ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).listarCreadoresPorMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse> WA_Prueba.CreadorMaterialWS.CreadorMaterialWS.listarCreadoresPorMaterialAsync(WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest request) {
            return base.Channel.listarCreadoresPorMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialResponse> listarCreadoresPorMaterialAsync(int idMaterial) {
            WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest inValue = new WA_Prueba.CreadorMaterialWS.listarCreadoresPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.CreadorMaterialWS.CreadorMaterialWS)(this)).listarCreadoresPorMaterialAsync(inValue);
        }
    }
}
