//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.PrestamoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="PrestamoWS.PrestamoWS")]
    public interface PrestamoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/eliminarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/eliminarPrestamoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.eliminarPrestamoResponse eliminarPrestamo(WA_Prueba.PrestamoWS.eliminarPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/eliminarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/eliminarPrestamoResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.eliminarPrestamoResponse> eliminarPrestamoAsync(WA_Prueba.PrestamoWS.eliminarPrestamoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/insertarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/insertarPrestamoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.insertarPrestamoResponse insertarPrestamo(WA_Prueba.PrestamoWS.insertarPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/insertarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/insertarPrestamoResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.insertarPrestamoResponse> insertarPrestamoAsync(WA_Prueba.PrestamoWS.insertarPrestamoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/obtenerPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/obtenerPrestamoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.obtenerPrestamoResponse obtenerPrestamo(WA_Prueba.PrestamoWS.obtenerPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/obtenerPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/obtenerPrestamoResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.obtenerPrestamoResponse> obtenerPrestamoAsync(WA_Prueba.PrestamoWS.obtenerPrestamoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/listarPrestamosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/listarPrestamosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.listarPrestamosResponse listarPrestamos(WA_Prueba.PrestamoWS.listarPrestamosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/listarPrestamosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/listarPrestamosResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.listarPrestamosResponse> listarPrestamosAsync(WA_Prueba.PrestamoWS.listarPrestamosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/modificarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/modificarPrestamoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.modificarPrestamoResponse modificarPrestamo(WA_Prueba.PrestamoWS.modificarPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/modificarPrestamoRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/modificarPrestamoResponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.modificarPrestamoResponse> modificarPrestamoAsync(WA_Prueba.PrestamoWS.modificarPrestamoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosActivosReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosActivosRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.contarPrestamosActivosResponse contarPrestamosActivos(WA_Prueba.PrestamoWS.contarPrestamosActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosActivosReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosActivosRespo" +
            "nse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosActivosResponse> contarPrestamosActivosAsync(WA_Prueba.PrestamoWS.contarPrestamosActivosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosPorMaterialR" +
            "equest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosPorMaterialR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse contarPrestamosPorMaterial(WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosPorMaterialR" +
            "equest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosPorMaterialR" +
            "esponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse> contarPrestamosPorMaterialAsync(WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosAtrasadosReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosAtrasadosRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse contarPrestamosAtrasados(WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosAtrasadosReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoWS/contarPrestamosAtrasadosRes" +
            "ponse")]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse> contarPrestamosAtrasadosAsync(WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamo", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        public eliminarPrestamoRequest() {
        }
        
        public eliminarPrestamoRequest(int idPrestamo) {
            this.idPrestamo = idPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamoResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPrestamoResponse() {
        }
        
        public eliminarPrestamoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamo", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaDevolucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public insertarPrestamoRequest() {
        }
        
        public insertarPrestamoRequest(System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            this.fechaSolicitud = fechaSolicitud;
            this.fechaPrestamo = fechaPrestamo;
            this.fechaDevolucion = fechaDevolucion;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamoResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPrestamoResponse() {
        }
        
        public insertarPrestamoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class prestamoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaDevolucionField;
        
        private bool fechaDevolucionFieldSpecified;
        
        private System.DateTime fechaPrestamoField;
        
        private bool fechaPrestamoFieldSpecified;
        
        private System.DateTime fechaSolicitudField;
        
        private bool fechaSolicitudFieldSpecified;
        
        private int idPrestamoField;
        
        private bool idPrestamoFieldSpecified;
        
        private personaDTO personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaDevolucion {
            get {
                return this.fechaDevolucionField;
            }
            set {
                this.fechaDevolucionField = value;
                this.RaisePropertyChanged("fechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDevolucionSpecified {
            get {
                return this.fechaDevolucionFieldSpecified;
            }
            set {
                this.fechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
                this.RaisePropertyChanged("fechaPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPrestamoSpecified {
            get {
                return this.fechaPrestamoFieldSpecified;
            }
            set {
                this.fechaPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                this.fechaSolicitudField = value;
                this.RaisePropertyChanged("fechaSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSolicitudSpecified {
            get {
                return this.fechaSolicitudFieldSpecified;
            }
            set {
                this.fechaSolicitudFieldSpecified = value;
                this.RaisePropertyChanged("fechaSolicitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                this.idPrestamoField = value;
                this.RaisePropertyChanged("idPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPrestamoSpecified {
            get {
                return this.idPrestamoFieldSpecified;
            }
            set {
                this.idPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("idPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public personaDTO persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class personaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenhaField;
        
        private string correoField;
        
        private string direccionField;
        
        private System.DateTime fechaContratoFinalField;
        
        private bool fechaContratoFinalFieldSpecified;
        
        private System.DateTime fechaContratoInicioField;
        
        private bool fechaContratoInicioFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string maternoField;
        
        private nivelDeIngles nivelField;
        
        private bool nivelFieldSpecified;
        
        private string nombreField;
        
        private string paternoField;
        
        private sedeDTO sedeField;
        
        private string telefonoField;
        
        private tipoPersona tipoField;
        
        private bool tipoFieldSpecified;
        
        private turnos turnoField;
        
        private bool turnoFieldSpecified;
        
        private bool vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaContratoFinal {
            get {
                return this.fechaContratoFinalField;
            }
            set {
                this.fechaContratoFinalField = value;
                this.RaisePropertyChanged("fechaContratoFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoFinalSpecified {
            get {
                return this.fechaContratoFinalFieldSpecified;
            }
            set {
                this.fechaContratoFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaContratoInicio {
            get {
                return this.fechaContratoInicioField;
            }
            set {
                this.fechaContratoInicioField = value;
                this.RaisePropertyChanged("fechaContratoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoInicioSpecified {
            get {
                return this.fechaContratoInicioFieldSpecified;
            }
            set {
                this.fechaContratoInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public nivelDeIngles nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public sedeDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public tipoPersona tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public turnos turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivelDeIngles {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoPersona {
        
        /// <remarks/>
        LECTOR,
        
        /// <remarks/>
        BIBLIOTECARIO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum turnos {
        
        /// <remarks/>
        MAÑANA,
        
        /// <remarks/>
        TARDE,
        
        /// <remarks/>
        NOCHE,
        
        /// <remarks/>
        FULLTIME,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamo", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        public obtenerPrestamoRequest() {
        }
        
        public obtenerPrestamoRequest(int idPrestamo) {
            this.idPrestamo = idPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamoResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoWS.prestamoDTO @return;
        
        public obtenerPrestamoResponse() {
        }
        
        public obtenerPrestamoResponse(WA_Prueba.PrestamoWS.prestamoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamos", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosRequest {
        
        public listarPrestamosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.PrestamoWS.prestamoDTO[] @return;
        
        public listarPrestamosResponse() {
        }
        
        public listarPrestamosResponse(WA_Prueba.PrestamoWS.prestamoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamo", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaDevolucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public modificarPrestamoRequest() {
        }
        
        public modificarPrestamoRequest(int idPrestamo, System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            this.idPrestamo = idPrestamo;
            this.fechaSolicitud = fechaSolicitud;
            this.fechaPrestamo = fechaPrestamo;
            this.fechaDevolucion = fechaDevolucion;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamoResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPrestamoResponse() {
        }
        
        public modificarPrestamoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosActivos", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosActivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public contarPrestamosActivosRequest() {
        }
        
        public contarPrestamosActivosRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosActivosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarPrestamosActivosResponse() {
        }
        
        public contarPrestamosActivosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosPorMaterial", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosPorMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public contarPrestamosPorMaterialRequest() {
        }
        
        public contarPrestamosPorMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosPorMaterialResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosPorMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarPrestamosPorMaterialResponse() {
        }
        
        public contarPrestamosPorMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosAtrasados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosAtrasadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public contarPrestamosAtrasadosRequest() {
        }
        
        public contarPrestamosAtrasadosRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPrestamosAtrasadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPrestamosAtrasadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarPrestamosAtrasadosResponse() {
        }
        
        public contarPrestamosAtrasadosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrestamoWSChannel : WA_Prueba.PrestamoWS.PrestamoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamoWSClient : System.ServiceModel.ClientBase<WA_Prueba.PrestamoWS.PrestamoWS>, WA_Prueba.PrestamoWS.PrestamoWS {
        
        public PrestamoWSClient() {
        }
        
        public PrestamoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.eliminarPrestamoResponse WA_Prueba.PrestamoWS.PrestamoWS.eliminarPrestamo(WA_Prueba.PrestamoWS.eliminarPrestamoRequest request) {
            return base.Channel.eliminarPrestamo(request);
        }
        
        public int eliminarPrestamo(int idPrestamo) {
            WA_Prueba.PrestamoWS.eliminarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.eliminarPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            WA_Prueba.PrestamoWS.eliminarPrestamoResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).eliminarPrestamo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.eliminarPrestamoResponse> WA_Prueba.PrestamoWS.PrestamoWS.eliminarPrestamoAsync(WA_Prueba.PrestamoWS.eliminarPrestamoRequest request) {
            return base.Channel.eliminarPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.eliminarPrestamoResponse> eliminarPrestamoAsync(int idPrestamo) {
            WA_Prueba.PrestamoWS.eliminarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.eliminarPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).eliminarPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.insertarPrestamoResponse WA_Prueba.PrestamoWS.PrestamoWS.insertarPrestamo(WA_Prueba.PrestamoWS.insertarPrestamoRequest request) {
            return base.Channel.insertarPrestamo(request);
        }
        
        public int insertarPrestamo(System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            WA_Prueba.PrestamoWS.insertarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.insertarPrestamoRequest();
            inValue.fechaSolicitud = fechaSolicitud;
            inValue.fechaPrestamo = fechaPrestamo;
            inValue.fechaDevolucion = fechaDevolucion;
            inValue.idPersona = idPersona;
            WA_Prueba.PrestamoWS.insertarPrestamoResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).insertarPrestamo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.insertarPrestamoResponse> WA_Prueba.PrestamoWS.PrestamoWS.insertarPrestamoAsync(WA_Prueba.PrestamoWS.insertarPrestamoRequest request) {
            return base.Channel.insertarPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.insertarPrestamoResponse> insertarPrestamoAsync(System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            WA_Prueba.PrestamoWS.insertarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.insertarPrestamoRequest();
            inValue.fechaSolicitud = fechaSolicitud;
            inValue.fechaPrestamo = fechaPrestamo;
            inValue.fechaDevolucion = fechaDevolucion;
            inValue.idPersona = idPersona;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).insertarPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.obtenerPrestamoResponse WA_Prueba.PrestamoWS.PrestamoWS.obtenerPrestamo(WA_Prueba.PrestamoWS.obtenerPrestamoRequest request) {
            return base.Channel.obtenerPrestamo(request);
        }
        
        public WA_Prueba.PrestamoWS.prestamoDTO obtenerPrestamo(int idPrestamo) {
            WA_Prueba.PrestamoWS.obtenerPrestamoRequest inValue = new WA_Prueba.PrestamoWS.obtenerPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            WA_Prueba.PrestamoWS.obtenerPrestamoResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).obtenerPrestamo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.obtenerPrestamoResponse> WA_Prueba.PrestamoWS.PrestamoWS.obtenerPrestamoAsync(WA_Prueba.PrestamoWS.obtenerPrestamoRequest request) {
            return base.Channel.obtenerPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.obtenerPrestamoResponse> obtenerPrestamoAsync(int idPrestamo) {
            WA_Prueba.PrestamoWS.obtenerPrestamoRequest inValue = new WA_Prueba.PrestamoWS.obtenerPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).obtenerPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.listarPrestamosResponse WA_Prueba.PrestamoWS.PrestamoWS.listarPrestamos(WA_Prueba.PrestamoWS.listarPrestamosRequest request) {
            return base.Channel.listarPrestamos(request);
        }
        
        public WA_Prueba.PrestamoWS.prestamoDTO[] listarPrestamos() {
            WA_Prueba.PrestamoWS.listarPrestamosRequest inValue = new WA_Prueba.PrestamoWS.listarPrestamosRequest();
            WA_Prueba.PrestamoWS.listarPrestamosResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).listarPrestamos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.listarPrestamosResponse> WA_Prueba.PrestamoWS.PrestamoWS.listarPrestamosAsync(WA_Prueba.PrestamoWS.listarPrestamosRequest request) {
            return base.Channel.listarPrestamosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.listarPrestamosResponse> listarPrestamosAsync() {
            WA_Prueba.PrestamoWS.listarPrestamosRequest inValue = new WA_Prueba.PrestamoWS.listarPrestamosRequest();
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).listarPrestamosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.modificarPrestamoResponse WA_Prueba.PrestamoWS.PrestamoWS.modificarPrestamo(WA_Prueba.PrestamoWS.modificarPrestamoRequest request) {
            return base.Channel.modificarPrestamo(request);
        }
        
        public int modificarPrestamo(int idPrestamo, System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            WA_Prueba.PrestamoWS.modificarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.modificarPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.fechaSolicitud = fechaSolicitud;
            inValue.fechaPrestamo = fechaPrestamo;
            inValue.fechaDevolucion = fechaDevolucion;
            inValue.idPersona = idPersona;
            WA_Prueba.PrestamoWS.modificarPrestamoResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).modificarPrestamo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.modificarPrestamoResponse> WA_Prueba.PrestamoWS.PrestamoWS.modificarPrestamoAsync(WA_Prueba.PrestamoWS.modificarPrestamoRequest request) {
            return base.Channel.modificarPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.modificarPrestamoResponse> modificarPrestamoAsync(int idPrestamo, System.DateTime fechaSolicitud, System.DateTime fechaPrestamo, System.DateTime fechaDevolucion, int idPersona) {
            WA_Prueba.PrestamoWS.modificarPrestamoRequest inValue = new WA_Prueba.PrestamoWS.modificarPrestamoRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.fechaSolicitud = fechaSolicitud;
            inValue.fechaPrestamo = fechaPrestamo;
            inValue.fechaDevolucion = fechaDevolucion;
            inValue.idPersona = idPersona;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).modificarPrestamoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.contarPrestamosActivosResponse WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosActivos(WA_Prueba.PrestamoWS.contarPrestamosActivosRequest request) {
            return base.Channel.contarPrestamosActivos(request);
        }
        
        public int contarPrestamosActivos(int idUsuario) {
            WA_Prueba.PrestamoWS.contarPrestamosActivosRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosActivosRequest();
            inValue.idUsuario = idUsuario;
            WA_Prueba.PrestamoWS.contarPrestamosActivosResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosActivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosActivosResponse> WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosActivosAsync(WA_Prueba.PrestamoWS.contarPrestamosActivosRequest request) {
            return base.Channel.contarPrestamosActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosActivosResponse> contarPrestamosActivosAsync(int idUsuario) {
            WA_Prueba.PrestamoWS.contarPrestamosActivosRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosActivosRequest();
            inValue.idUsuario = idUsuario;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosPorMaterial(WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest request) {
            return base.Channel.contarPrestamosPorMaterial(request);
        }
        
        public int contarPrestamosPorMaterial(int idMaterial) {
            WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosPorMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse> WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosPorMaterialAsync(WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest request) {
            return base.Channel.contarPrestamosPorMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosPorMaterialResponse> contarPrestamosPorMaterialAsync(int idMaterial) {
            WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosPorMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosAtrasados(WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest request) {
            return base.Channel.contarPrestamosAtrasados(request);
        }
        
        public int contarPrestamosAtrasados(int idUsuario) {
            WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest();
            inValue.idUsuario = idUsuario;
            WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse retVal = ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosAtrasados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse> WA_Prueba.PrestamoWS.PrestamoWS.contarPrestamosAtrasadosAsync(WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest request) {
            return base.Channel.contarPrestamosAtrasadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.PrestamoWS.contarPrestamosAtrasadosResponse> contarPrestamosAtrasadosAsync(int idUsuario) {
            WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest inValue = new WA_Prueba.PrestamoWS.contarPrestamosAtrasadosRequest();
            inValue.idUsuario = idUsuario;
            return ((WA_Prueba.PrestamoWS.PrestamoWS)(this)).contarPrestamosAtrasadosAsync(inValue);
        }
    }
}
