//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.EjemplarWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="EjemplarWS.EjemplarWS")]
    public interface EjemplarWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/insertarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/insertarEjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.insertarEjemplarResponse insertarEjemplar(WA_Prueba.EjemplarWS.insertarEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/insertarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/insertarEjemplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.insertarEjemplarResponse> insertarEjemplarAsync(WA_Prueba.EjemplarWS.insertarEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/obtenerEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/obtenerEjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.obtenerEjemplarResponse obtenerEjemplar(WA_Prueba.EjemplarWS.obtenerEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/obtenerEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/obtenerEjemplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.obtenerEjemplarResponse> obtenerEjemplarAsync(WA_Prueba.EjemplarWS.obtenerEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.contarTotalPorSedeResponse contarTotalPorSede(WA_Prueba.EjemplarWS.contarTotalPorSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorSedeResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorSedeResponse> contarTotalPorSedeAsync(WA_Prueba.EjemplarWS.contarTotalPorSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/eliminarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/eliminarEjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.eliminarEjemplarResponse eliminarEjemplar(WA_Prueba.EjemplarWS.eliminarEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/eliminarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/eliminarEjemplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.eliminarEjemplarResponse> eliminarEjemplarAsync(WA_Prueba.EjemplarWS.eliminarEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/modificarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/modificarEjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.modificarEjemplarResponse modificarEjemplar(WA_Prueba.EjemplarWS.modificarEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/modificarEjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/modificarEjemplarResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.modificarEjemplarResponse> modificarEjemplarAsync(WA_Prueba.EjemplarWS.modificarEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/listarEjemplaresRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/listarEjemplaresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.listarEjemplaresResponse listarEjemplares(WA_Prueba.EjemplarWS.listarEjemplaresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/listarEjemplaresRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/listarEjemplaresResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.listarEjemplaresResponse> listarEjemplaresAsync(WA_Prueba.EjemplarWS.listarEjemplaresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorMateria" +
            "lRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorMateria" +
            "lResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse contarDisponiblesPorMaterial(WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorMateria" +
            "lRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorMateria" +
            "lResponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse> contarDisponiblesPorMaterialAsync(WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorSedeReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorSedeRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse contarDisponiblesPorSede(WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorSedeReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarDisponiblesPorSedeRes" +
            "ponse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse> contarDisponiblesPorSedeAsync(WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorMaterialReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorMaterialRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse contarTotalPorMaterial(WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorMaterialReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/EjemplarWS/contarTotalPorMaterialRespo" +
            "nse")]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse> contarTotalPorMaterialAsync(WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoEjemplar {
        
        /// <remarks/>
        FISICO,
        
        /// <remarks/>
        DIGITAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum formatoDigital {
        
        /// <remarks/>
        MP3,
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        CBR,
        
        /// <remarks/>
        PPT,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaAdquisicion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool disponible;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.tipoEjemplar tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.formatoDigital formatoDigital;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ubicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public insertarEjemplarRequest() {
        }
        
        public insertarEjemplarRequest(System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            this.fechaAdquisicion = fechaAdquisicion;
            this.disponible = disponible;
            this.tipo = tipo;
            this.formatoDigital = formatoDigital;
            this.ubicacion = ubicacion;
            this.idSede = idSede;
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEjemplarResponse() {
        }
        
        public insertarEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class ejemplarDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool disponibleField;
        
        private bool disponibleFieldSpecified;
        
        private System.DateTime fechaAdquisicionField;
        
        private bool fechaAdquisicionFieldSpecified;
        
        private formatoDigital formatoDigitalField;
        
        private bool formatoDigitalFieldSpecified;
        
        private int idEjemplarField;
        
        private bool idEjemplarFieldSpecified;
        
        private materialDTO materialField;
        
        private sedeDTO sedeField;
        
        private tipoEjemplar tipoField;
        
        private bool tipoFieldSpecified;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
                this.RaisePropertyChanged("disponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibleSpecified {
            get {
                return this.disponibleFieldSpecified;
            }
            set {
                this.disponibleFieldSpecified = value;
                this.RaisePropertyChanged("disponibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaAdquisicion {
            get {
                return this.fechaAdquisicionField;
            }
            set {
                this.fechaAdquisicionField = value;
                this.RaisePropertyChanged("fechaAdquisicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAdquisicionSpecified {
            get {
                return this.fechaAdquisicionFieldSpecified;
            }
            set {
                this.fechaAdquisicionFieldSpecified = value;
                this.RaisePropertyChanged("fechaAdquisicionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public formatoDigital formatoDigital {
            get {
                return this.formatoDigitalField;
            }
            set {
                this.formatoDigitalField = value;
                this.RaisePropertyChanged("formatoDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatoDigitalSpecified {
            get {
                return this.formatoDigitalFieldSpecified;
            }
            set {
                this.formatoDigitalFieldSpecified = value;
                this.RaisePropertyChanged("formatoDigitalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEjemplar {
            get {
                return this.idEjemplarField;
            }
            set {
                this.idEjemplarField = value;
                this.RaisePropertyChanged("idEjemplar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEjemplarSpecified {
            get {
                return this.idEjemplarFieldSpecified;
            }
            set {
                this.idEjemplarFieldSpecified = value;
                this.RaisePropertyChanged("idEjemplarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public sedeDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoEjemplar tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string edicionField;
        
        private editorialDTO editorialField;
        
        private int idMaterialField;
        
        private bool idMaterialFieldSpecified;
        
        private nivelDeIngles nivelField;
        
        private bool nivelFieldSpecified;
        
        private string portadaField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string edicion {
            get {
                return this.edicionField;
            }
            set {
                this.edicionField = value;
                this.RaisePropertyChanged("edicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public editorialDTO editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idMaterial {
            get {
                return this.idMaterialField;
            }
            set {
                this.idMaterialField = value;
                this.RaisePropertyChanged("idMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMaterialSpecified {
            get {
                return this.idMaterialFieldSpecified;
            }
            set {
                this.idMaterialFieldSpecified = value;
                this.RaisePropertyChanged("idMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public nivelDeIngles nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class editorialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEditorialField;
        
        private bool idEditorialFieldSpecified;
        
        private string nombreField;
        
        private string paisField;
        
        private string sitioWebField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEditorialSpecified {
            get {
                return this.idEditorialFieldSpecified;
            }
            set {
                this.idEditorialFieldSpecified = value;
                this.RaisePropertyChanged("idEditorialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sitioWeb {
            get {
                return this.sitioWebField;
            }
            set {
                this.sitioWebField = value;
                this.RaisePropertyChanged("sitioWeb");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivelDeIngles {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public obtenerEjemplarRequest() {
        }
        
        public obtenerEjemplarRequest(int idEjemplar) {
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.ejemplarDTO @return;
        
        public obtenerEjemplarResponse() {
        }
        
        public obtenerEjemplarResponse(WA_Prueba.EjemplarWS.ejemplarDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarTotalPorSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarTotalPorSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public contarTotalPorSedeRequest() {
        }
        
        public contarTotalPorSedeRequest(int idSede) {
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarTotalPorSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarTotalPorSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarTotalPorSedeResponse() {
        }
        
        public contarTotalPorSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public eliminarEjemplarRequest() {
        }
        
        public eliminarEjemplarRequest(int idEjemplar) {
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEjemplarResponse() {
        }
        
        public eliminarEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaAdquisicion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool disponible;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.tipoEjemplar tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.formatoDigital formatoDigital;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ubicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public modificarEjemplarRequest() {
        }
        
        public modificarEjemplarRequest(int idEjemplar, System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            this.idEjemplar = idEjemplar;
            this.fechaAdquisicion = fechaAdquisicion;
            this.disponible = disponible;
            this.tipo = tipo;
            this.formatoDigital = formatoDigital;
            this.ubicacion = ubicacion;
            this.idSede = idSede;
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEjemplarResponse() {
        }
        
        public modificarEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEjemplares", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarEjemplaresRequest {
        
        public listarEjemplaresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEjemplaresResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarEjemplaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.EjemplarWS.ejemplarDTO[] @return;
        
        public listarEjemplaresResponse() {
        }
        
        public listarEjemplaresResponse(WA_Prueba.EjemplarWS.ejemplarDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarDisponiblesPorMaterial", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarDisponiblesPorMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public contarDisponiblesPorMaterialRequest() {
        }
        
        public contarDisponiblesPorMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarDisponiblesPorMaterialResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarDisponiblesPorMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarDisponiblesPorMaterialResponse() {
        }
        
        public contarDisponiblesPorMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarDisponiblesPorSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarDisponiblesPorSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public contarDisponiblesPorSedeRequest() {
        }
        
        public contarDisponiblesPorSedeRequest(int idSede) {
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarDisponiblesPorSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarDisponiblesPorSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarDisponiblesPorSedeResponse() {
        }
        
        public contarDisponiblesPorSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarTotalPorMaterial", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarTotalPorMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public contarTotalPorMaterialRequest() {
        }
        
        public contarTotalPorMaterialRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarTotalPorMaterialResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarTotalPorMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarTotalPorMaterialResponse() {
        }
        
        public contarTotalPorMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EjemplarWSChannel : WA_Prueba.EjemplarWS.EjemplarWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemplarWSClient : System.ServiceModel.ClientBase<WA_Prueba.EjemplarWS.EjemplarWS>, WA_Prueba.EjemplarWS.EjemplarWS {
        
        public EjemplarWSClient() {
        }
        
        public EjemplarWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemplarWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplarWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplarWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.insertarEjemplarResponse WA_Prueba.EjemplarWS.EjemplarWS.insertarEjemplar(WA_Prueba.EjemplarWS.insertarEjemplarRequest request) {
            return base.Channel.insertarEjemplar(request);
        }
        
        public int insertarEjemplar(System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            WA_Prueba.EjemplarWS.insertarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.insertarEjemplarRequest();
            inValue.fechaAdquisicion = fechaAdquisicion;
            inValue.disponible = disponible;
            inValue.tipo = tipo;
            inValue.formatoDigital = formatoDigital;
            inValue.ubicacion = ubicacion;
            inValue.idSede = idSede;
            inValue.idMaterial = idMaterial;
            WA_Prueba.EjemplarWS.insertarEjemplarResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).insertarEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.insertarEjemplarResponse> WA_Prueba.EjemplarWS.EjemplarWS.insertarEjemplarAsync(WA_Prueba.EjemplarWS.insertarEjemplarRequest request) {
            return base.Channel.insertarEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.insertarEjemplarResponse> insertarEjemplarAsync(System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            WA_Prueba.EjemplarWS.insertarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.insertarEjemplarRequest();
            inValue.fechaAdquisicion = fechaAdquisicion;
            inValue.disponible = disponible;
            inValue.tipo = tipo;
            inValue.formatoDigital = formatoDigital;
            inValue.ubicacion = ubicacion;
            inValue.idSede = idSede;
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).insertarEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.obtenerEjemplarResponse WA_Prueba.EjemplarWS.EjemplarWS.obtenerEjemplar(WA_Prueba.EjemplarWS.obtenerEjemplarRequest request) {
            return base.Channel.obtenerEjemplar(request);
        }
        
        public WA_Prueba.EjemplarWS.ejemplarDTO obtenerEjemplar(int idEjemplar) {
            WA_Prueba.EjemplarWS.obtenerEjemplarRequest inValue = new WA_Prueba.EjemplarWS.obtenerEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            WA_Prueba.EjemplarWS.obtenerEjemplarResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).obtenerEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.obtenerEjemplarResponse> WA_Prueba.EjemplarWS.EjemplarWS.obtenerEjemplarAsync(WA_Prueba.EjemplarWS.obtenerEjemplarRequest request) {
            return base.Channel.obtenerEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.obtenerEjemplarResponse> obtenerEjemplarAsync(int idEjemplar) {
            WA_Prueba.EjemplarWS.obtenerEjemplarRequest inValue = new WA_Prueba.EjemplarWS.obtenerEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).obtenerEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.contarTotalPorSedeResponse WA_Prueba.EjemplarWS.EjemplarWS.contarTotalPorSede(WA_Prueba.EjemplarWS.contarTotalPorSedeRequest request) {
            return base.Channel.contarTotalPorSede(request);
        }
        
        public int contarTotalPorSede(int idSede) {
            WA_Prueba.EjemplarWS.contarTotalPorSedeRequest inValue = new WA_Prueba.EjemplarWS.contarTotalPorSedeRequest();
            inValue.idSede = idSede;
            WA_Prueba.EjemplarWS.contarTotalPorSedeResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarTotalPorSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorSedeResponse> WA_Prueba.EjemplarWS.EjemplarWS.contarTotalPorSedeAsync(WA_Prueba.EjemplarWS.contarTotalPorSedeRequest request) {
            return base.Channel.contarTotalPorSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorSedeResponse> contarTotalPorSedeAsync(int idSede) {
            WA_Prueba.EjemplarWS.contarTotalPorSedeRequest inValue = new WA_Prueba.EjemplarWS.contarTotalPorSedeRequest();
            inValue.idSede = idSede;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarTotalPorSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.eliminarEjemplarResponse WA_Prueba.EjemplarWS.EjemplarWS.eliminarEjemplar(WA_Prueba.EjemplarWS.eliminarEjemplarRequest request) {
            return base.Channel.eliminarEjemplar(request);
        }
        
        public int eliminarEjemplar(int idEjemplar) {
            WA_Prueba.EjemplarWS.eliminarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.eliminarEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            WA_Prueba.EjemplarWS.eliminarEjemplarResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).eliminarEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.eliminarEjemplarResponse> WA_Prueba.EjemplarWS.EjemplarWS.eliminarEjemplarAsync(WA_Prueba.EjemplarWS.eliminarEjemplarRequest request) {
            return base.Channel.eliminarEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.eliminarEjemplarResponse> eliminarEjemplarAsync(int idEjemplar) {
            WA_Prueba.EjemplarWS.eliminarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.eliminarEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).eliminarEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.modificarEjemplarResponse WA_Prueba.EjemplarWS.EjemplarWS.modificarEjemplar(WA_Prueba.EjemplarWS.modificarEjemplarRequest request) {
            return base.Channel.modificarEjemplar(request);
        }
        
        public int modificarEjemplar(int idEjemplar, System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            WA_Prueba.EjemplarWS.modificarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.modificarEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            inValue.fechaAdquisicion = fechaAdquisicion;
            inValue.disponible = disponible;
            inValue.tipo = tipo;
            inValue.formatoDigital = formatoDigital;
            inValue.ubicacion = ubicacion;
            inValue.idSede = idSede;
            inValue.idMaterial = idMaterial;
            WA_Prueba.EjemplarWS.modificarEjemplarResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).modificarEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.modificarEjemplarResponse> WA_Prueba.EjemplarWS.EjemplarWS.modificarEjemplarAsync(WA_Prueba.EjemplarWS.modificarEjemplarRequest request) {
            return base.Channel.modificarEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.modificarEjemplarResponse> modificarEjemplarAsync(int idEjemplar, System.DateTime fechaAdquisicion, bool disponible, WA_Prueba.EjemplarWS.tipoEjemplar tipo, WA_Prueba.EjemplarWS.formatoDigital formatoDigital, string ubicacion, int idSede, int idMaterial) {
            WA_Prueba.EjemplarWS.modificarEjemplarRequest inValue = new WA_Prueba.EjemplarWS.modificarEjemplarRequest();
            inValue.idEjemplar = idEjemplar;
            inValue.fechaAdquisicion = fechaAdquisicion;
            inValue.disponible = disponible;
            inValue.tipo = tipo;
            inValue.formatoDigital = formatoDigital;
            inValue.ubicacion = ubicacion;
            inValue.idSede = idSede;
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).modificarEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.listarEjemplaresResponse WA_Prueba.EjemplarWS.EjemplarWS.listarEjemplares(WA_Prueba.EjemplarWS.listarEjemplaresRequest request) {
            return base.Channel.listarEjemplares(request);
        }
        
        public WA_Prueba.EjemplarWS.ejemplarDTO[] listarEjemplares() {
            WA_Prueba.EjemplarWS.listarEjemplaresRequest inValue = new WA_Prueba.EjemplarWS.listarEjemplaresRequest();
            WA_Prueba.EjemplarWS.listarEjemplaresResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).listarEjemplares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.listarEjemplaresResponse> WA_Prueba.EjemplarWS.EjemplarWS.listarEjemplaresAsync(WA_Prueba.EjemplarWS.listarEjemplaresRequest request) {
            return base.Channel.listarEjemplaresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.listarEjemplaresResponse> listarEjemplaresAsync() {
            WA_Prueba.EjemplarWS.listarEjemplaresRequest inValue = new WA_Prueba.EjemplarWS.listarEjemplaresRequest();
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).listarEjemplaresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse WA_Prueba.EjemplarWS.EjemplarWS.contarDisponiblesPorMaterial(WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest request) {
            return base.Channel.contarDisponiblesPorMaterial(request);
        }
        
        public int contarDisponiblesPorMaterial(int idMaterial) {
            WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest inValue = new WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarDisponiblesPorMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse> WA_Prueba.EjemplarWS.EjemplarWS.contarDisponiblesPorMaterialAsync(WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest request) {
            return base.Channel.contarDisponiblesPorMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialResponse> contarDisponiblesPorMaterialAsync(int idMaterial) {
            WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest inValue = new WA_Prueba.EjemplarWS.contarDisponiblesPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarDisponiblesPorMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse WA_Prueba.EjemplarWS.EjemplarWS.contarDisponiblesPorSede(WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest request) {
            return base.Channel.contarDisponiblesPorSede(request);
        }
        
        public int contarDisponiblesPorSede(int idSede) {
            WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest inValue = new WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest();
            inValue.idSede = idSede;
            WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarDisponiblesPorSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse> WA_Prueba.EjemplarWS.EjemplarWS.contarDisponiblesPorSedeAsync(WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest request) {
            return base.Channel.contarDisponiblesPorSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarDisponiblesPorSedeResponse> contarDisponiblesPorSedeAsync(int idSede) {
            WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest inValue = new WA_Prueba.EjemplarWS.contarDisponiblesPorSedeRequest();
            inValue.idSede = idSede;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarDisponiblesPorSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse WA_Prueba.EjemplarWS.EjemplarWS.contarTotalPorMaterial(WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest request) {
            return base.Channel.contarTotalPorMaterial(request);
        }
        
        public int contarTotalPorMaterial(int idMaterial) {
            WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest inValue = new WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse retVal = ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarTotalPorMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse> WA_Prueba.EjemplarWS.EjemplarWS.contarTotalPorMaterialAsync(WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest request) {
            return base.Channel.contarTotalPorMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.EjemplarWS.contarTotalPorMaterialResponse> contarTotalPorMaterialAsync(int idMaterial) {
            WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest inValue = new WA_Prueba.EjemplarWS.contarTotalPorMaterialRequest();
            inValue.idMaterial = idMaterial;
            return ((WA_Prueba.EjemplarWS.EjemplarWS)(this)).contarTotalPorMaterialAsync(inValue);
        }
    }
}
