//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Prueba.SedeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="SedeWS.SedeWS")]
    public interface SedeWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/obtenerSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/obtenerSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.SedeWS.obtenerSedeResponse obtenerSede(WA_Prueba.SedeWS.obtenerSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/obtenerSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/obtenerSedeResponse")]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.obtenerSedeResponse> obtenerSedeAsync(WA_Prueba.SedeWS.obtenerSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/modificarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/modificarSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.SedeWS.modificarSedeResponse modificarSede(WA_Prueba.SedeWS.modificarSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/modificarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/modificarSedeResponse")]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.modificarSedeResponse> modificarSedeAsync(WA_Prueba.SedeWS.modificarSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/eliminarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/eliminarSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.SedeWS.eliminarSedeResponse eliminarSede(WA_Prueba.SedeWS.eliminarSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/eliminarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/eliminarSedeResponse")]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.eliminarSedeResponse> eliminarSedeAsync(WA_Prueba.SedeWS.eliminarSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/listarSedesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/listarSedesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.SedeWS.listarSedesResponse listarSedes(WA_Prueba.SedeWS.listarSedesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/listarSedesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/listarSedesResponse")]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.listarSedesResponse> listarSedesAsync(WA_Prueba.SedeWS.listarSedesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/insertarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/insertarSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WA_Prueba.SedeWS.insertarSedeResponse insertarSede(WA_Prueba.SedeWS.insertarSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SedeWS/insertarSedeRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SedeWS/insertarSedeResponse")]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.insertarSedeResponse> insertarSedeAsync(WA_Prueba.SedeWS.insertarSedeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public obtenerSedeRequest() {
        }
        
        public obtenerSedeRequest(int idSede) {
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.SedeWS.sedeDTO @return;
        
        public obtenerSedeResponse() {
        }
        
        public obtenerSedeResponse(WA_Prueba.SedeWS.sedeDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefonoContacto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoContacto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activa;
        
        public modificarSedeRequest() {
        }
        
        public modificarSedeRequest(int idSede, string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            this.idSede = idSede;
            this.nombre = nombre;
            this.direccion = direccion;
            this.distrito = distrito;
            this.telefonoContacto = telefonoContacto;
            this.correoContacto = correoContacto;
            this.activa = activa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarSedeResponse() {
        }
        
        public modificarSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public eliminarSedeRequest() {
        }
        
        public eliminarSedeRequest(int idSede) {
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarSedeResponse() {
        }
        
        public eliminarSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSedes", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSedesRequest {
        
        public listarSedesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSedesResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSedesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WA_Prueba.SedeWS.sedeDTO[] @return;
        
        public listarSedesResponse() {
        }
        
        public listarSedesResponse(WA_Prueba.SedeWS.sedeDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSede", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string distrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefonoContacto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoContacto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activa;
        
        public insertarSedeRequest() {
        }
        
        public insertarSedeRequest(string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            this.nombre = nombre;
            this.direccion = direccion;
            this.distrito = distrito;
            this.telefonoContacto = telefonoContacto;
            this.correoContacto = correoContacto;
            this.activa = activa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSedeResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSedeResponse() {
        }
        
        public insertarSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SedeWSChannel : WA_Prueba.SedeWS.SedeWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SedeWSClient : System.ServiceModel.ClientBase<WA_Prueba.SedeWS.SedeWS>, WA_Prueba.SedeWS.SedeWS {
        
        public SedeWSClient() {
        }
        
        public SedeWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SedeWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedeWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedeWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.SedeWS.obtenerSedeResponse WA_Prueba.SedeWS.SedeWS.obtenerSede(WA_Prueba.SedeWS.obtenerSedeRequest request) {
            return base.Channel.obtenerSede(request);
        }
        
        public WA_Prueba.SedeWS.sedeDTO obtenerSede(int idSede) {
            WA_Prueba.SedeWS.obtenerSedeRequest inValue = new WA_Prueba.SedeWS.obtenerSedeRequest();
            inValue.idSede = idSede;
            WA_Prueba.SedeWS.obtenerSedeResponse retVal = ((WA_Prueba.SedeWS.SedeWS)(this)).obtenerSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.obtenerSedeResponse> WA_Prueba.SedeWS.SedeWS.obtenerSedeAsync(WA_Prueba.SedeWS.obtenerSedeRequest request) {
            return base.Channel.obtenerSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.SedeWS.obtenerSedeResponse> obtenerSedeAsync(int idSede) {
            WA_Prueba.SedeWS.obtenerSedeRequest inValue = new WA_Prueba.SedeWS.obtenerSedeRequest();
            inValue.idSede = idSede;
            return ((WA_Prueba.SedeWS.SedeWS)(this)).obtenerSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.SedeWS.modificarSedeResponse WA_Prueba.SedeWS.SedeWS.modificarSede(WA_Prueba.SedeWS.modificarSedeRequest request) {
            return base.Channel.modificarSede(request);
        }
        
        public int modificarSede(int idSede, string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            WA_Prueba.SedeWS.modificarSedeRequest inValue = new WA_Prueba.SedeWS.modificarSedeRequest();
            inValue.idSede = idSede;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.distrito = distrito;
            inValue.telefonoContacto = telefonoContacto;
            inValue.correoContacto = correoContacto;
            inValue.activa = activa;
            WA_Prueba.SedeWS.modificarSedeResponse retVal = ((WA_Prueba.SedeWS.SedeWS)(this)).modificarSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.modificarSedeResponse> WA_Prueba.SedeWS.SedeWS.modificarSedeAsync(WA_Prueba.SedeWS.modificarSedeRequest request) {
            return base.Channel.modificarSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.SedeWS.modificarSedeResponse> modificarSedeAsync(int idSede, string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            WA_Prueba.SedeWS.modificarSedeRequest inValue = new WA_Prueba.SedeWS.modificarSedeRequest();
            inValue.idSede = idSede;
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.distrito = distrito;
            inValue.telefonoContacto = telefonoContacto;
            inValue.correoContacto = correoContacto;
            inValue.activa = activa;
            return ((WA_Prueba.SedeWS.SedeWS)(this)).modificarSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.SedeWS.eliminarSedeResponse WA_Prueba.SedeWS.SedeWS.eliminarSede(WA_Prueba.SedeWS.eliminarSedeRequest request) {
            return base.Channel.eliminarSede(request);
        }
        
        public int eliminarSede(int idSede) {
            WA_Prueba.SedeWS.eliminarSedeRequest inValue = new WA_Prueba.SedeWS.eliminarSedeRequest();
            inValue.idSede = idSede;
            WA_Prueba.SedeWS.eliminarSedeResponse retVal = ((WA_Prueba.SedeWS.SedeWS)(this)).eliminarSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.eliminarSedeResponse> WA_Prueba.SedeWS.SedeWS.eliminarSedeAsync(WA_Prueba.SedeWS.eliminarSedeRequest request) {
            return base.Channel.eliminarSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.SedeWS.eliminarSedeResponse> eliminarSedeAsync(int idSede) {
            WA_Prueba.SedeWS.eliminarSedeRequest inValue = new WA_Prueba.SedeWS.eliminarSedeRequest();
            inValue.idSede = idSede;
            return ((WA_Prueba.SedeWS.SedeWS)(this)).eliminarSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.SedeWS.listarSedesResponse WA_Prueba.SedeWS.SedeWS.listarSedes(WA_Prueba.SedeWS.listarSedesRequest request) {
            return base.Channel.listarSedes(request);
        }
        
        public WA_Prueba.SedeWS.sedeDTO[] listarSedes() {
            WA_Prueba.SedeWS.listarSedesRequest inValue = new WA_Prueba.SedeWS.listarSedesRequest();
            WA_Prueba.SedeWS.listarSedesResponse retVal = ((WA_Prueba.SedeWS.SedeWS)(this)).listarSedes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.listarSedesResponse> WA_Prueba.SedeWS.SedeWS.listarSedesAsync(WA_Prueba.SedeWS.listarSedesRequest request) {
            return base.Channel.listarSedesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.SedeWS.listarSedesResponse> listarSedesAsync() {
            WA_Prueba.SedeWS.listarSedesRequest inValue = new WA_Prueba.SedeWS.listarSedesRequest();
            return ((WA_Prueba.SedeWS.SedeWS)(this)).listarSedesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WA_Prueba.SedeWS.insertarSedeResponse WA_Prueba.SedeWS.SedeWS.insertarSede(WA_Prueba.SedeWS.insertarSedeRequest request) {
            return base.Channel.insertarSede(request);
        }
        
        public int insertarSede(string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            WA_Prueba.SedeWS.insertarSedeRequest inValue = new WA_Prueba.SedeWS.insertarSedeRequest();
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.distrito = distrito;
            inValue.telefonoContacto = telefonoContacto;
            inValue.correoContacto = correoContacto;
            inValue.activa = activa;
            WA_Prueba.SedeWS.insertarSedeResponse retVal = ((WA_Prueba.SedeWS.SedeWS)(this)).insertarSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WA_Prueba.SedeWS.insertarSedeResponse> WA_Prueba.SedeWS.SedeWS.insertarSedeAsync(WA_Prueba.SedeWS.insertarSedeRequest request) {
            return base.Channel.insertarSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WA_Prueba.SedeWS.insertarSedeResponse> insertarSedeAsync(string nombre, string direccion, string distrito, string telefonoContacto, string correoContacto, bool activa) {
            WA_Prueba.SedeWS.insertarSedeRequest inValue = new WA_Prueba.SedeWS.insertarSedeRequest();
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.distrito = distrito;
            inValue.telefonoContacto = telefonoContacto;
            inValue.correoContacto = correoContacto;
            inValue.activa = activa;
            return ((WA_Prueba.SedeWS.SedeWS)(this)).insertarSedeAsync(inValue);
        }
    }
}
